[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "youtube-channel-monitor"
version ="0.1.0"
description = "Python program that monitors YouTube channels for new uploads."
requires-python = ">=3.11"

dependencies = [
    "requests",
    "feedparser",
    "python-dotenv",
    "yt-dlp",
]

[project.scripts]
ytmonitor = "youtube_channel_monitor.main:main"


[tool.setuptools.packages.find]
where = ["src"]
